In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os,sys
%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# for auto-reloading external modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

In [2]:
#testing environment 
class Action_Space(object):
    def __init__(self, n):
        self.n = n 
    
my_action= Action_Space(10)
    
class Env(object):
    
    def __init__(self, obs_space, action_space):
        self.observation_space = obs_space
        self.action_space = action_space

my_obs_space = np.ones([10,5])

my_env = Env(my_obs_space, my_action)        


my_feature_columns = []
for key in ['aa','bb','cc']:
    my_feature_columns.append(tf.feature_column.numeric_column(key=key))

In [3]:
my_feature_columns

[_NumericColumn(key='aa', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='bb', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='cc', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [6]:
import network

dirname = os.getcwd()
VF_model_dir = os.path.join(dirname, 'tmp/VF/')

VF_CONFIG = {'feature_columns': my_feature_columns,
            'model_dir':VF_model_dir,
             'hidden_units':[100,100],
             'n_classes':3
            }

In [25]:
import sys,os
sys.path.append(os.path.realpath('..'))

In [46]:
vf= network.ValueF_net(my_env,config=VF_CONFIG)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/lh/4rk5gl355k14pkvt29spw0mh0000gn/T/tmpy1wg7j5z', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x11edd11d0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [7]:
VF_model_dir
#dirname
vf.classifier.get_variable_names()

NameError: name 'vf' is not defined

In [17]:
PN_CONFIG = {'model_dir':None,
             'hidden_units':[100,100],
             'input_D':5,
             'n_classes':3
            }

network.Policy_net(my_env, PN_CONFIG)

In [19]:
#tf.reset_default_graph()
tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)

[<tf.Variable 'policy_net/dense_0/kernel:0' shape=(5, 100) dtype=float32_ref>,
 <tf.Variable 'policy_net/dense_0/bias:0' shape=(100,) dtype=float32_ref>,
 <tf.Variable 'policy_net/dense_1/kernel:0' shape=(100, 100) dtype=float32_ref>,
 <tf.Variable 'policy_net/dense_1/bias:0' shape=(100,) dtype=float32_ref>,
 <tf.Variable 'policy_net/dense_2/kernel:0' shape=(100, 5) dtype=float32_ref>,
 <tf.Variable 'policy_net/dense_2/bias:0' shape=(5,) dtype=float32_ref>]

In [70]:
x = {'a':1, 'b':2}
y ={'a':2, 'c':3}
#x.update()

for k in x.items():
    print(k)


('a', 1)
('b', 2)


In [71]:
tf.reset_default_graph()

a= tf.get_variable("my_int_variable", [1, 3, 4], dtype=tf.int32,
  initializer=tf.zeros_initializer)

b = tf.get_variable("my_int_variable2", [1, 2, 6], dtype=tf.int32,
  initializer=tf.zeros_initializer)

tmp = [a, b]
print(tf.reshape(a, [12]))
print(tf.reshape(b, [12]))

c= tf.concat([tf.reshape(a, [12]), tf.reshape(b, [12])],axis=0)
print(c)

Tensor("Reshape:0", shape=(12,), dtype=int32)
Tensor("Reshape_1:0", shape=(12,), dtype=int32)
Tensor("concat:0", shape=(24,), dtype=int32)


EVerytime you use initializaer you will reset the value of your variable to how you initialize them.

In [54]:
#op1 = tf.add(a, 2)
#a= a+2
#g= a+1
op1= tf.assign(a, a+2)
op2= tf.assign(b, b+5)
#op3= tf.assign(c,c+10)


op_all = tf.group(*[op1, op2])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(op_all)
    sess.run(op_all)
    print(c)
    print(sess.run(c))
    #print(sess.run(a))
    sess.run(tf.global_variables_initializer())
    sess.run(op_all)
    sess.run(op_all)
    print(sess.run(c))
    

Tensor("concat:0", shape=(24,), dtype=int32)
[ 4  4  4  4  4  4  4  4  4  4  4  4 10 10 10 10 10 10 10 10 10 10 10 10]
[ 4  4  4  4  4  4  4  4  4  4  4  4 10 10 10 10 10 10 10 10 10 10 10 10]


In [69]:
tf.reset_default_graph()


a= tf.placeholder(name='haha', shape=[None,], dtype=tf.int32)

#b= tf.get_variable("my_int_variable1", [2,], dtype=tf.int32,
#  initializer=tf.zeros_initializer)
#c= tf.get_variable("my_int_variable2", [3,], dtype=tf.int32,
#  initializer=tf.zeros_initializer)
b= np.array([1,2])
c= np.array([1,2,3])


N = tf.shape(a)[0]

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    #sess.run(a,feed_dict={a:b})
    
    #cannot use haha to refer to the operation
    print(sess.run(N,feed_dict={a:b}))
    #sess.run(a,feed_dict={a:c})
    print(sess.run(N,feed_dict={a:c}))
    
    

TypeError: Cannot interpret feed_dict key as Tensor: The name 'haha' refers to an Operation, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".

In [73]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    #print(sess.run(op1))
    for i in range(3):
        print(a)
        print(sess.run(a))


<tf.Variable 'my_int_variable:0' shape=(1, 3, 4) dtype=int32_ref>
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<tf.Variable 'my_int_variable:0' shape=(1, 3, 4) dtype=int32_ref>
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<tf.Variable 'my_int_variable:0' shape=(1, 3, 4) dtype=int32_ref>
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


tf.global_variables_initializer() run后重新初始化为开始的初始值

In [89]:
op1 = c + np.ones(shape=[24])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(c))
    print(c.copy())
    print(sess.run(op1))
    print(np.ones(c.shape))
    print('Assignment')
    print(sess.run(tf.assign(a, np.ones(shape=[1,3,4]))))
    print(sess.run(a))
    

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


AttributeError: 'Tensor' object has no attribute 'copy'

Can be used to assign value from numpy directly

In [90]:
k = tf.identity(c)
op1 = tf.assign(a, a+2)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(c))
    print(sess.run(op1))
    print(sess.run(c))
    print(sess.run(k))
    

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]
[2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0]
[2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0]


In [95]:
a = tf.constant(0.)
b = 2 * a
g = tf.gradients(a + b, [a, b], stop_gradients=[a, b])

with tf.Session() as sess:
    print(type(sess.run(g)[0]))


<class 'numpy.float32'>


In [98]:
import tensorflow as tf
import numpy as np

f = tf.Variable(np.array([[1., 2., 0]]).T)
loss = tf.reduce_prod(f ** 2 - 3 * f + 1)

first_derivatives = tf.gradients(loss, f)[0]

second_derivatives = tf.gradients(first_derivatives, f)[0]

hessian = [tf.gradients(first_derivatives[i,0], f)[0][:,0] for i in range(3)]

model = tf.initialize_all_variables()
with tf.Session() as sess:
    sess.run(model)
    print("\nloss\n", sess.run(loss))
    tmp = sess.run(first_derivatives)
    second_derivatives = tf.gradients(tmp, f)
    print("\nloss\n", sess.run(second_derivatives))



loss
 1.0


TypeError: Fetch argument None has invalid type <class 'NoneType'>

In [1]:
import tensorflow as tf
import argparse
import gym.spaces
import gym

import os
import utils
import trpo
from atari_setter import *



tf.reset_default_graph()

env_id = 'CartPole-v0'


sess = tf.Session()
init = tf.global_variables_initializer()


workerseed = 2012
set_global_seeds(workerseed)

env = make_atari(env_id)
#env = gym.make(env_id)

usr_cfg = {}
usr_cfg['feature_columns'] = []

usr_cfg['feature_columns'].append(tf.feature_column.numeric_column("x", shape = [4], dtype=tf.float64))
cur_dir = os.getcwd()
cur_dir = os.path.join(cur_dir, 'tmp/VF')
usr_cfg['model_dir']= cur_dir


trpo_updater = trpo.TRPO_Updater(sess, env, usr_cfg)
sess.run(init)


while(trpo_updater.train):
    paths = utils.rollout(env, trpo_updater.policy_net, 10000, 1000)
    trpo_updater.learn(paths)

    
    
#for _ in range(1000): # run for 1000 steps
#    env.render()
#    action = env.action_space.sample() # pick a random action
#    print(action)
#    break
#    observation, reward, done, info = env.step(action) # take action
#    
#    print(observation)
#    print(reward)
#env = bench.Monitor(env, logger.get_dir() and osp.join(logger.get_dir(), str(rank)))
#env.seed(workerseed)

#env = wrap_deepmind(env)
#env.seed(workerseed)

#trpo_mpi.learn(env, policy_fn, timesteps_per_batch=512, max_kl=0.001, cg_iters=10, cg_damping=1e-3,
#    max_timesteps=int(num_timesteps * 1.1), gamma=0.98, lam=1.0, vf_iters=3, vf_stepsize=1e-4, entcoeff=0.00)
env.close()

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/Users/lihaonan/myproject/TRPO/tmp/VF', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1230b1d30>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


We have 291 number of paths for training Value network.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-470
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 471 into /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt.
INFO:tensorflow:loss = 7.230094, step = 471
INFO:tensorflow:global_step/sec: 616.903
INFO:tensorflow:loss = 3.5445495, step = 571 (0.163 sec)
INFO:tensorflow:global_step/sec: 856.811
INFO:tensorflow:loss = 6.0550356, step = 671 (0.116 sec)
INFO:tensorflow:Saving checkpoints for 705 into /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt.
INFO:tensorflow:Loss for final step: 4.9678597.
[-2.18307041e-03  1.10508315e-03 -5.61454399e-05  2.42617098e-05
 -1.35189493e-03  5.87261573e-04 -8.65275739e-04 -9.01616149e-0

w is 
[ 2.51012389e-03 -1.35885924e-03  1.88706399e-05  1.60177910e-06
  1.87384209e-03 -4.87328012e-04  8.13708932e-04  1.49913094e-05
 -7.36212125e-04  3.68991787e-05 -5.10711761e-05 -7.23774720e-05
 -7.70799408e-04  7.53347471e-04  9.02349479e-04 -7.06007654e-07
  1.27843785e-04  2.21262639e-03  1.55871781e-03  1.34023197e-03
  5.27310483e-02 -5.64464107e-02 -1.47608025e-05 -6.38932670e-06
  6.59362376e-02  4.87623550e-03 -2.91522359e-03  3.57112276e-06
 -3.78598757e-02  2.92155182e-05 -4.96744688e-05 -4.99402918e-03
  4.16946923e-03  1.66478530e-02  2.21226159e-02 -9.71344434e-06
  1.56755075e-02  4.59620692e-02  6.03721514e-02  5.33515476e-02
 -4.24132310e-03  1.94198743e-03  4.91092287e-05 -1.00262205e-05
 -2.83188955e-03  9.86550353e-04 -1.55750790e-03  3.00794964e-05
  1.04156439e-03  2.17846864e-05 -6.84860788e-05  2.06299694e-04
  1.56408816e-03 -1.14353443e-03 -2.34507234e-03  3.17920349e-05
 -1.13726928e-04 -3.84199922e-03 -2.49216054e-03 -2.05333228e-03
 -8.95634368e-02  9

[ 2.51012389e-03 -1.35885924e-03  1.88706399e-05  1.60177910e-06
  1.87384209e-03 -4.87328012e-04  8.13708932e-04  1.49913094e-05
 -7.36212125e-04  3.68991787e-05 -5.10711761e-05 -7.23774720e-05
 -7.70799408e-04  7.53347471e-04  9.02349479e-04 -7.06007654e-07
  1.27843785e-04  2.21262639e-03  1.55871781e-03  1.34023197e-03
  5.27310483e-02 -5.64464107e-02 -1.47608025e-05 -6.38932670e-06
  6.59362376e-02  4.87623550e-03 -2.91522359e-03  3.57112276e-06
 -3.78598757e-02  2.92155182e-05 -4.96744688e-05 -4.99402918e-03
  4.16946923e-03  1.66478530e-02  2.21226159e-02 -9.71344434e-06
  1.56755075e-02  4.59620692e-02  6.03721514e-02  5.33515476e-02
 -4.24132310e-03  1.94198743e-03  4.91092287e-05 -1.00262205e-05
 -2.83188955e-03  9.86550353e-04 -1.55750790e-03  3.00794964e-05
  1.04156439e-03  2.17846864e-05 -6.84860788e-05  2.06299694e-04
  1.56408816e-03 -1.14353443e-03 -2.34507234e-03  3.17920349e-05
 -1.13726928e-04 -3.84199922e-03 -2.49216054e-03 -2.05333228e-03
 -8.95634368e-02  9.12953

/Users/lihaonan/myproject/TRPO/trpo.py:154: RuntimeWarning: divide by zero encountered in float_scalars
  alpha = rho / p.dot(w)
/Users/lihaonan/myproject/TRPO/trpo.py:155: RuntimeWarning: invalid value encountered in multiply
  x += alpha * p
/Users/lihaonan/myproject/TRPO/trpo.py:156: RuntimeWarning: invalid value encountered in multiply
  r -= alpha * w


Total number of episodes:                 291
Average sum of rewards per episode:       11.786941580756015
Entropy:                                  0.684832
Baseline explained:                       0.0
Time elapsed:                             0.03 mins
KL between old and new distribution:      1.45712e-09
Surrogate loss:                           2.1674417e-08
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done cal

INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO

INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Don

INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO

INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Don

INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO

INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Don

INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO

INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Don

INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO

INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /Users/lihaonan/myproject/TRPO/tmp/VF/model.ckpt-705
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Don

w is 
[ 3.24503431e-04 -8.67431372e-05  4.58559907e-06  5.82770781e-06
  1.05776744e-04 -1.16943855e-04  1.89443948e-04  9.15916098e-06
 -8.44541137e-06  2.35831358e-05 -3.97812873e-05 -2.90819371e-05
 -1.98434616e-04  7.91152925e-05  1.63763340e-04  1.07667574e-06
 -4.40668809e-05  3.09673167e-04  7.67362362e-05 -5.38900349e-06
  7.24581210e-03 -6.66360278e-03 -7.95357118e-06 -9.62617719e-08
  7.88118783e-03  9.43160703e-05  4.41748154e-04  1.96100227e-05
 -4.37794905e-03  1.51995164e-05 -5.81763597e-05 -7.97733315e-04
 -4.09425178e-04  2.08680169e-03  3.52156488e-03  6.22544394e-06
  1.57604378e-03  6.48101652e-03  7.31796119e-03  6.11507194e-03
 -6.16368023e-04  1.41832890e-04  4.88759397e-05 -1.04712981e-05
 -2.82720954e-04  2.01578427e-04 -2.98943312e-04  2.38273005e-05
  4.45415099e-05  1.33881240e-05 -5.19232053e-05  2.09258287e-05
  2.91763456e-04 -1.47447703e-04 -3.82419326e-04  2.72720590e-05
 -6.80643097e-07 -5.85695496e-04 -2.53559207e-04 -2.15666587e-04
 -1.27852811e-02  1

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan na

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan na

In [5]:


for _ in range(1000): # run for 1000 steps
    env.render()
    action = trpo # pick a random action
    print(action)
    break
    observation, reward, done, info = env.step(action) # take action

[{'obs': array([[ 0.01009484, -0.01533948, -0.03953246,  0.01996335],
         [-0.00249772, -0.59905815, -0.00429342,  1.14790285],
         [-0.07382127, -1.37992239,  0.12309825,  2.361696  ]]),
  'act_dists': array([[0.50088316, 0.4991168 ],
         [0.5469788 , 0.45302117],
         [0.6013232 , 0.39867672]], dtype=float32),
  'rewards': array([4., 4., 2.]),
  'acts': array([0, 0, 0]),
  'baseline': [{'predictions': 11.825050354003906},
   {'predictions': 6.047351360321045},
   {'predictions': 1.8318647146224976},
   {'predictions': 11.825050354003906},
   {'predictions': 6.047351360321045},
   {'predictions': 1.8318647146224976},
   {'predictions': 11.825050354003906},
   {'predictions': 6.047351360321045},
   {'predictions': 1.8318647146224976},
   {'predictions': 11.825050354003906},
   {'predictions': 6.047351360321045},
   {'predictions': 1.8318647146224976},
   {'predictions': 11.825050354003906},
   {'predictions': 6.047351360321045},
   {'predictions': 1.8318647146224976}

In [3]:
len(paths)

for p in paths:
    print(len(p['obs']))

9
19
13
13
10
15
14
16


In [64]:
#env.observation_space
#env.action_space.n
utils.rollout(env, trpo_updater.policy_net, 10000, 1000)


obs dim is (1, 4)
action is: [[0.50400186 0.4959982 ]]
action distribution is  [0]


In [4]:
import numpy as np
a= np.array([1]).reshape([1,1])
a.squeeze()

()

numpy array squeeze test, it will squeeze (1,1) to scalar ()

In [5]:
#paths[1]['obs'].shape
np.concatenate([np.array((1,2)).reshape(1,2),np.array((1,2)).reshape(1,2)]).shape

(2, 2)

In [9]:
import scipy.signal
x = np.array([1,2,3,4,5]).reshape([1,5])

#x = np.array([1,2,3,4,5])

scipy.signal.lfilter([1],[1,-0.5],x[::-1], axis=0)[::-1]

array([[1., 2., 3., 4., 5.]])

test behaviour of the reward calculation function